create table balance (
	balance_id INT,
	user_id INT,
	transaction_id INT
);
insert into balance (balance_id, user_id, transaction_id) values (1, 74, 38);
insert into balance (balance_id, user_id, transaction_id) values (2, 60, 85);
insert into balance (balance_id, user_id, transaction_id) values (3, 71, 72);
insert into balance (balance_id, user_id, transaction_id) values (4, 89, 42);
insert into balance (balance_id, user_id, transaction_id) values (5, 21, 100);
insert into balance (balance_id, user_id, transaction_id) values (6, 64, 75);
insert into balance (balance_id, user_id, transaction_id) values (7, 94, 63);
insert into balance (balance_id, user_id, transaction_id) values (8, 26, 51);
insert into balance (balance_id, user_id, transaction_id) values (9, 39, 91);
insert into balance (balance_id, user_id, transaction_id) values (10, 23, 100);
insert into balance (balance_id, user_id, transaction_id) values (11, 31, 76);
insert into balance (balance_id, user_id, transaction_id) values (12, 90, 18);
insert into balance (balance_id, user_id, transaction_id) values (13, 38, 52);
insert into balance (balance_id, user_id, transaction_id) values (14, 68, 73);
insert into balance (balance_id, user_id, transaction_id) values (15, 100, 70);
insert into balance (balance_id, user_id, transaction_id) values (16, 18, 4);
insert into balance (balance_id, user_id, transaction_id) values (17, 40, 50);
insert into balance (balance_id, user_id, transaction_id) values (18, 56, 51);
insert into balance (balance_id, user_id, transaction_id) values (19, 66, 79);
insert into balance (balance_id, user_id, transaction_id) values (20, 40, 23);
insert into balance (balance_id, user_id, transaction_id) values (21, 59, 84);
insert into balance (balance_id, user_id, transaction_id) values (22, 68, 9);
insert into balance (balance_id, user_id, transaction_id) values (23, 98, 30);
insert into balance (balance_id, user_id, transaction_id) values (24, 76, 16);
insert into balance (balance_id, user_id, transaction_id) values (25, 77, 68);
insert into balance (balance_id, user_id, transaction_id) values (26, 67, 28);
insert into balance (balance_id, user_id, transaction_id) values (27, 41, 29);
insert into balance (balance_id, user_id, transaction_id) values (28, 30, 44);
insert into balance (balance_id, user_id, transaction_id) values (29, 26, 18);
insert into balance (balance_id, user_id, transaction_id) values (30, 64, 33);
insert into balance (balance_id, user_id, transaction_id) values (31, 17, 24);
insert into balance (balance_id, user_id, transaction_id) values (32, 11, 24);
insert into balance (balance_id, user_id, transaction_id) values (33, 94, 74);
insert into balance (balance_id, user_id, transaction_id) values (34, 12, 43);
insert into balance (balance_id, user_id, transaction_id) values (35, 47, 48);
insert into balance (balance_id, user_id, transaction_id) values (36, 91, 77);
insert into balance (balance_id, user_id, transaction_id) values (37, 51, 37);
insert into balance (balance_id, user_id, transaction_id) values (38, 10, 71);
insert into balance (balance_id, user_id, transaction_id) values (39, 21, 81);
insert into balance (balance_id, user_id, transaction_id) values (40, 66, 86);
insert into balance (balance_id, user_id, transaction_id) values (41, 31, 85);
insert into balance (balance_id, user_id, transaction_id) values (42, 69, 56);
insert into balance (balance_id, user_id, transaction_id) values (43, 38, 36);
insert into balance (balance_id, user_id, transaction_id) values (44, 60, 58);
insert into balance (balance_id, user_id, transaction_id) values (45, 16, 84);
insert into balance (balance_id, user_id, transaction_id) values (46, 20, 77);
insert into balance (balance_id, user_id, transaction_id) values (47, 45, 97);
insert into balance (balance_id, user_id, transaction_id) values (48, 60, 76);
insert into balance (balance_id, user_id, transaction_id) values (49, 78, 74);
insert into balance (balance_id, user_id, transaction_id) values (50, 68, 57);
